// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://behgtjynoxayuvsumtid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaGd0anlub3hheXV2c3VtdGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzYyMzgsImV4cCI6MjA2NDcxMjIzOH0.iXw_mZONAijsloo_9Xif97l3gV3ZIJZ1_DxA2DUsakg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);